import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraAppProvider } from "./providers/ChakraProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>Root</h1>
        <ChakraAppProvider>{children}</ChakraAppProvider>
      </body>
    </html>
  );
}
